### ISSUE TITLE
Getting Error 3 - DupecheckArgUnresolved

### ISSUE THREAD

**Issue by Vaarelsauce** [Altrentorae/osuMusicLibExtractor#1]
I've extracted the file onto my desktop. 

Ran MusicLibGeneratorGUI.exe as admin.

Selected the osu's Song folder.

Selected an output folder on my desktop as the Target Directory.

Checked .inin index and Skip same osu! IDs.

But when I press Start, it throws that error.

**Comment by Vaarelsauce** [comment]
Okay so I renamed the output folder to "output2" instead of "output 2", and it seemed to fix. HOWEVER, I do get an error a few seconds in while letting the program do its thing, telling me to check the error log. I've attached it below.

[ErrLog.log](https://github.com/Altrentorae/osuMusicLibExtractor/files/9075677/ErrLog.log)

**Comment by Altrentorae** [comment]
I've released a new version to address these issues. The first issue involving spaces should be fixed entirely, while the second issue is a lot tougher to resolve, and instead it'll now skip files where the path is too long.

https://github.com/Altrentorae/osuMusicLibExtractor/releases/tag/v0.6

Closing this for now, feel free to reopen if the issues aren't properly resolved.
