### ISSUE TITLE
Possible to also implement cover art extraction?

### ISSUE THREAD

**Issue by Vaarelsauce** [Altrentorae/osuMusicLibExtractor#2]
I'm not sure how the metadata ripping works, but assuming that everything is located in one folder (.mp3, title, artist, cover), I would guess that it's plausible to make a feature where the extracted song also comes with its respective cover art? (like say, search for .jpg/jpeg/png)

I know one of the [old osu! Music Exporter](https://github.com/Modricagon/Osu-Music-Exporter/releases) was able to do this, but it's very old and clunky so I'm assuming the coding are drastically different.

![osu! music exporter artwork option](https://user-images.githubusercontent.com/36707936/178095509-bd0911e6-70e8-4382-99e3-6b3c76b98f0e.png)

**Comment by Altrentorae** [comment]
I will look into adding this at some point soon, no promises though :)

**Comment by Altrentorae** [comment]
Added in [v0.61](https://github.com/Altrentorae/osuMusicLibExtractor/releases/tag/v0.61)
