### ISSUE TITLE
Option for Romaji titles only? ("corrupted titles" issue)

### ISSUE THREAD

**Issue by Vaarelsauce** [Altrentorae/osuMusicLibExtractor#4]
Some of the songs I've downloaded are titled very strangely, and some of which makes it almost impossible to understand what it's named, let alone trying to search for its name. I know that (iirc) in-game all of the song have Romaji titles, so that they won't appear cursed like some of these titles down here...

![3](https://user-images.githubusercontent.com/36707936/178608696-b9c71cca-4bb5-4fff-9074-97530bc74451.png)

(these two pictures are after importing the songs into iTunes)
![1](https://user-images.githubusercontent.com/36707936/178607350-d3aa65c9-f6c6-4163-879d-0357aa16f13c.png)
![2](https://user-images.githubusercontent.com/36707936/178607356-3621ec83-7f7a-46c1-a351-a6a6d37f0e19.png)

**Comment by Altrentorae** [comment]
Made some changes and adjustments for the title and artist fields. [v0.61](https://github.com/Altrentorae/osuMusicLibExtractor/releases/tag/v0.61).
